#############################################################################
# Makefile for building: SimpGCS
# Generated by qmake (2.01a) (Qt 4.8.6) on: Mon Jul 6 21:07:46 2015
# Project:  SimpGCS.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile SimpGCS.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_DECLARATIVE_LIB -DQT_SVG_LIB -DQT_SQL_LIB -DQT_XML_LIB -DQT_OPENGL_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtOpenGL -I/usr/include/qt4/QtXml -I/usr/include/qt4/QtSql -I/usr/include/qt4/QtSvg -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -Ilibs -Ilibs/rtk++/include -Ilibs/opmapcontrol/core -Ilibs/opmapcontrol/internals -Ilibs/opmapcontrol/mapwidget -I/usr/X11R6/include -Ibuild
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -L/usr/X11R6/lib64 ./libs/rtk++/lib/librtk_osa.a ./libs/rtk++/lib/librtk_utils.a -lQGLViewer -lGLU ./libs/opmapcontrol/libopmapwidget.a -lQtDeclarative -lQtSvg -lQtSql -lQtXml -lQtOpenGL -lQtGui -lQtNetwork -lQtCore -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/GCS_MainWindow.cpp \
		src/qFlightInstruments.cpp \
		src/MapWidget.cpp \
		src/utils_UART.cpp \
		src/utils_GPS.cpp \
		src/utils_mavlink.cpp \
		src/UAS.cpp \
		src/SimpGCS.cpp build/moc_GCS_MainWindow.cpp \
		build/moc_qFlightInstruments.cpp \
		build/moc_MapWidget.cpp \
		qrc_mapresources.cpp
OBJECTS       = build/GCS_MainWindow.o \
		build/qFlightInstruments.o \
		build/MapWidget.o \
		build/utils_UART.o \
		build/utils_GPS.o \
		build/utils_mavlink.o \
		build/UAS.o \
		build/SimpGCS.o \
		build/moc_GCS_MainWindow.o \
		build/moc_qFlightInstruments.o \
		build/moc_MapWidget.o \
		build/qrc_mapresources.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		SimpGCS.pro
QMAKE_TARGET  = SimpGCS
DESTDIR       = 
TARGET        = SimpGCS

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SimpGCS.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/opengl.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/lib/x86_64-linux-gnu/libQGLViewer.prl \
		/usr/lib/x86_64-linux-gnu/libQtDeclarative.prl \
		/usr/lib/x86_64-linux-gnu/libQtSvg.prl \
		/usr/lib/x86_64-linux-gnu/libQtSql.prl \
		/usr/lib/x86_64-linux-gnu/libQtXml.prl \
		/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl \
		/usr/lib/x86_64-linux-gnu/libQtGui.prl \
		/usr/lib/x86_64-linux-gnu/libQtNetwork.prl \
		/usr/lib/x86_64-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile SimpGCS.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/opengl.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/lib/x86_64-linux-gnu/libQGLViewer.prl:
/usr/lib/x86_64-linux-gnu/libQtDeclarative.prl:
/usr/lib/x86_64-linux-gnu/libQtSvg.prl:
/usr/lib/x86_64-linux-gnu/libQtSql.prl:
/usr/lib/x86_64-linux-gnu/libQtXml.prl:
/usr/lib/x86_64-linux-gnu/libQtOpenGL.prl:
/usr/lib/x86_64-linux-gnu/libQtGui.prl:
/usr/lib/x86_64-linux-gnu/libQtNetwork.prl:
/usr/lib/x86_64-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile SimpGCS.pro

dist: 
	@$(CHK_DIR_EXISTS) build/SimpGCS1.0.0 || $(MKDIR) build/SimpGCS1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/SimpGCS1.0.0/ && $(COPY_FILE) --parents src/GCS_MainWindow.h src/qFlightInstruments.h src/MapWidget.h src/utils_UART.h src/utils_GPS.h src/utils_mavlink.h src/UAS.h build/SimpGCS1.0.0/ && $(COPY_FILE) --parents libs/opmapcontrol/mapwidget/mapresources.qrc build/SimpGCS1.0.0/ && $(COPY_FILE) --parents src/GCS_MainWindow.cpp src/qFlightInstruments.cpp src/MapWidget.cpp src/utils_UART.cpp src/utils_GPS.cpp src/utils_mavlink.cpp src/UAS.cpp src/SimpGCS.cpp build/SimpGCS1.0.0/ && (cd `dirname build/SimpGCS1.0.0` && $(TAR) SimpGCS1.0.0.tar SimpGCS1.0.0 && $(COMPRESS) SimpGCS1.0.0.tar) && $(MOVE) `dirname build/SimpGCS1.0.0`/SimpGCS1.0.0.tar.gz . && $(DEL_FILE) -r build/SimpGCS1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_GCS_MainWindow.cpp build/moc_qFlightInstruments.cpp build/moc_MapWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_GCS_MainWindow.cpp build/moc_qFlightInstruments.cpp build/moc_MapWidget.cpp
build/moc_GCS_MainWindow.cpp: src/qFlightInstruments.h \
		src/MapWidget.h \
		src/UAS.h \
		src/utils_mavlink.h \
		src/GCS_MainWindow.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/GCS_MainWindow.h -o build/moc_GCS_MainWindow.cpp

build/moc_qFlightInstruments.cpp: src/qFlightInstruments.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/qFlightInstruments.h -o build/moc_qFlightInstruments.cpp

build/moc_MapWidget.cpp: src/MapWidget.h
	/usr/lib/x86_64-linux-gnu/qt4/bin/moc $(DEFINES) $(INCPATH) src/MapWidget.h -o build/moc_MapWidget.cpp

compiler_rcc_make_all: qrc_mapresources.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mapresources.cpp
qrc_mapresources.cpp: libs/opmapcontrol/mapwidget/mapresources.qrc \
		libs/opmapcontrol/mapwidget/images/EasystarBlue.png \
		libs/opmapcontrol/mapwidget/images/airplanepip.png \
		libs/opmapcontrol/mapwidget/images/mapquad.png \
		libs/opmapcontrol/mapwidget/images/dragons2.jpeg \
		libs/opmapcontrol/mapwidget/images/compas.svg \
		libs/opmapcontrol/mapwidget/images/home.svg \
		libs/opmapcontrol/mapwidget/images/EasystarBlue.png \
		libs/opmapcontrol/mapwidget/images/home2.svg \
		libs/opmapcontrol/mapwidget/images/marker.png \
		libs/opmapcontrol/mapwidget/images/airplanepip.png \
		libs/opmapcontrol/mapwidget/images/mapquad.png \
		libs/opmapcontrol/mapwidget/images/dragons1.jpg \
		libs/opmapcontrol/mapwidget/images/bigMarkerGreen.png \
		libs/opmapcontrol/mapwidget/images/home.png \
		libs/opmapcontrol/mapwidget/images/airplane.svg
	/usr/lib/x86_64-linux-gnu/qt4/bin/rcc -name mapresources libs/opmapcontrol/mapwidget/mapresources.qrc -o qrc_mapresources.cpp

compiler_image_collection_make_all: build/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) build/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

build/GCS_MainWindow.o: src/GCS_MainWindow.cpp src/GCS_MainWindow.h \
		src/qFlightInstruments.h \
		src/MapWidget.h \
		src/UAS.h \
		src/utils_mavlink.h \
		src/utils_GPS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/GCS_MainWindow.o src/GCS_MainWindow.cpp

build/qFlightInstruments.o: src/qFlightInstruments.cpp src/qFlightInstruments.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qFlightInstruments.o src/qFlightInstruments.cpp

build/MapWidget.o: src/MapWidget.cpp src/MapWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/MapWidget.o src/MapWidget.cpp

build/utils_UART.o: src/utils_UART.cpp src/utils_UART.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/utils_UART.o src/utils_UART.cpp

build/utils_GPS.o: src/utils_GPS.cpp src/utils_GPS.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/utils_GPS.o src/utils_GPS.cpp

build/utils_mavlink.o: src/utils_mavlink.cpp src/utils_mavlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/utils_mavlink.o src/utils_mavlink.cpp

build/UAS.o: src/UAS.cpp src/UAS.h \
		src/utils_mavlink.h \
		src/qFlightInstruments.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/UAS.o src/UAS.cpp

build/SimpGCS.o: src/SimpGCS.cpp src/utils_UART.h \
		src/GCS_MainWindow.h \
		src/qFlightInstruments.h \
		src/MapWidget.h \
		src/UAS.h \
		src/utils_mavlink.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/SimpGCS.o src/SimpGCS.cpp

build/moc_GCS_MainWindow.o: build/moc_GCS_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_GCS_MainWindow.o build/moc_GCS_MainWindow.cpp

build/moc_qFlightInstruments.o: build/moc_qFlightInstruments.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_qFlightInstruments.o build/moc_qFlightInstruments.cpp

build/moc_MapWidget.o: build/moc_MapWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_MapWidget.o build/moc_MapWidget.cpp

build/qrc_mapresources.o: qrc_mapresources.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_mapresources.o qrc_mapresources.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

